import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "./MuiThemeProvider";
import Header from "@/components/layout/header/Header";

const notoSansThai = Noto_Sans_Thai({
    subsets: ["thai", "latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-noto-sans-thai",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="th">
            <body className={`${notoSansThai.variable}`}>
                <MuiThemeProvider>
                    <Header />
                    {children}
                </MuiThemeProvider>
            </body>
        </html>
    );
}
