import { GoogleTagManager } from "@next/third-parties/google";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "./MuiThemeProvider";
import Header from "@/components/layout/header/Header";

const gscid = process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID;
const gtmId = process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID;

const notoSansThai = Noto_Sans_Thai({
    subsets: ["thai", "latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-noto-sans-thai",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    verification: { google: gscid },
};

export default function RootLayout({ children }) {
    return (
        <html lang="th">
            <GoogleTagManager gtmId={gtmId} />
            <body className={`${notoSansThai.variable}`}>
                <MuiThemeProvider>
                    <Header />
                    {children}
                </MuiThemeProvider>
            </body>
        </html>
    );
}
